---
title: "Welcome"
toc: true
toc-location: right
---

# Introduction to Reproducibility with R

## Overview

An increase in the complexity and scale of biological data means
biologists are increasingly required to develop the data skills needed
to design reproducible workflows for the simulation, collection,
organisation, processing, analysis and presentation of data. Developing
such data skills requires at least some coding, also known as scripting.
This makes your work (everything you do with your raw data) explicitly
described, totally transparent and completely reproducible. However,
learning to code can be a daunting prospect for many biologists! That’s
where Reproducibility with R comes in!

R is a free and open source language especially well-suited to data
analysis and visualisation and has a relatively inclusive and
newbie-friendly community. R caters to users who do not see themselves
as programmers, but then allows them to slide gradually into
programming.

This workshop will introduce you to R and RStudio, the most widely used
interface for working with R. You will learn how to import data,
manipulate it, summarise it and plot it. You will learn how to use an
organised project-oriented workflow with well commented scripts so that
you can understand your work in the future, and share it with others. In
addition, you will learn what a working directory and a file path are -
these are key concepts in computing generally but ones which are often
not taught to biologists.

## Philosophy and approach

It is impossible to cover everything you might ever need! Different
people will use different methods and tools. Topics have been chosen
because they are: foundational, widely applicable and transferable
conceptually.

## Learning outcomes

After this workshop the successful learner will be able to:

- explain what an operating system is and the organisation of files and directories in a file system
- explain root, home and working directories along with absolute and relative file paths
- find their way around the RStudio windows, use an RStudio Project to organise work and a script to run commands
- use the R command line to create and use the basic data types in R
- distinguish between continuous and discrete variables and be able to appropriately summarise and plot them in R import data in to RStudio from a variety of file types
- explain what is meant by ‘tidy’ data and organise data in spreadsheets.
- customise and save publication quality figures
- Use and modify R workflows for qPCR analysis, RNA sequence analysis, flow cytometry analysis or ImageJ files

## About the instructor

Emma Rand is a Professor in the Department of Biology at the University
of York where she specialises in teaching data science and
reproducibility, particularly to those who do not see themselves as
programmers. She leads UKRI funded projects called
[Cloud-SPAN](https://cloud-span.york.ac.uk/) and the [UKRI Digital
Research Skills Catalyst](https://digitalskillscatalyst.ac.uk/) that
train the research workforce in digital research skills using Findable,
Accessible, Interoperable and Reusable (FAIR) materials.
